rancher:
  hostname: rancher.34.125.130.100.nip.io

  service:
    type: "NodePort"

  ingress:
    ingressClassName: "nginx"

  replicas: 1

  bootstrapPassword: admin

  global:
    cattle:
      psp:
        # default is true for K8s version 1.24 and below, and false for 1.25 and above
        enabled: false
