- hosts: all
  name: fetch kubeconfig file
  gather_facts: false
  become: yes
  tasks:
  - name: fetch kubeconfig file
    ansible.builtin.fetch:
      src: /home/k8sgcp/.kube/config
      dest: /root/k8s-terraform/rke2/
      flat: yes
      validate_checksum: false
