apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: loki
    meta.helm.sh/release-namespace: logging
  labels:
    app.kubernetes.io/component: memcached-chunks-cache
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki
  name: loki-chunks-cache
  namespace: logging
spec:
  clusterIP: None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: memcached-client
      port: 11211
      protocol: TCP
      targetPort: 11211
    - name: http-metrics
      port: 9150
      protocol: TCP
      targetPort: 9150
  selector:
    app.kubernetes.io/component: memcached-chunks-cache
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: loki
  sessionAffinity: None
  type: ClusterIP
