apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: loki
    meta.helm.sh/release-namespace: logging
  labels:
    app.kubernetes.io/name: loki
  name: loki-runtime
  namespace: logging
data:
  runtime-config.yaml: |
    {}
