apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: loki
    meta.helm.sh/release-namespace: logging
  labels:
    app.kubernetes.io/name: loki
  name: loki
  namespace: logging
data:
  config.yaml: |2
    auth_enabled: false
    chunk_store_config:
      chunk_cache_config:
        background:
          writeback_buffer: 500000
          writeback_goroutines: 1
          writeback_size_limit: 500MB
        default_validity: 0s
        memcached:
          batch_size: 4
          parallelism: 5
        memcached_client:
          addresses: dnssrvnoa+_memcached-client._tcp.loki-chunks-cache.logging.svc
          consistent_hash: true
          max_idle_conns: 72
          timeout: 2000ms
    common:
      compactor_address: 'http://loki-backend:3100'
      path_prefix: /var/loki
      replication_factor: 3
      storage:
        s3:
          access_key_id: ${MINIO_ACCESS_KEY_ID}
          bucketnames: lokik8sminio
          endpoint: http://minio-svc.minio-store.svc.cluster.local:9000
          http_config:
            idle_conn_timeout: 90s
            response_header_timeout: 0s
          insecure: false
          region: minio
          s3forcepathstyle: true
          secret_access_key: ${MINIO_SECRET_ACCESS_KEY}
    frontend:
      scheduler_address: ""
      tail_proxy_url: http://loki-querier.logging.svc.cluster.local:3100
    frontend_worker:
      scheduler_address: ""
    index_gateway:
      mode: simple
    limits_config:
      max_cache_freshness_per_query: 10m
      max_global_streams_per_user: 10000
      max_query_series: 10000
      query_timeout: 300s
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      retention_period: 4d
      split_queries_by_interval: 15m
      volume_enabled: true
    memberlist:
      join_members:
      - loki-memberlist
    pattern_ingester:
      enabled: false
    query_range:
      align_queries_with_step: true
      cache_results: true
      results_cache:
        cache:
          background:
            writeback_buffer: 500000
            writeback_goroutines: 1
            writeback_size_limit: 500MB
          default_validity: 12h
          memcached_client:
            addresses: dnssrvnoa+_memcached-client._tcp.loki-results-cache.logging.svc
            consistent_hash: true
            timeout: 500ms
            update_interval: 1m
    ruler:
      alertmanager_url: http://kubemon-alertmanager.monitoring.svc.cluster.local:9093
      enable_alertmanager_v2: true
      enable_api: true
      ring:
        kvstore:
          store: inmemory
      rule_path: /temp/loki/rules
      storage:
        local:
          directory: /var/loki/rules
        type: local
    runtime_config:
      file: /etc/loki/runtime-config/runtime-config.yaml
    # To enable log retaintion comment out below three      
    #table_manager:
      #retention_deletes_enabled: true
      #retention_period: 24h      
    schema_config:
      configs:
      - from: "2024-04-01"
        index:
          period: 24h
          prefix: index_
        object_store: s3
        schema: v13
        store: tsdb
    server:
      grpc_listen_port: 9095
      http_listen_port: 3100
      http_server_read_timeout: 600s
      http_server_write_timeout: 600s
    storage_config:
      boltdb_shipper:
        index_gateway_client:
          server_address: dns+loki-backend-headless.logging.svc.cluster.local:9095
      hedging:
        at: 250ms
        max_per_second: 20
        up_to: 3
      tsdb_shipper:
        index_gateway_client:
          server_address: dns+loki-backend-headless.logging.svc.cluster.local:9095
    tracing:
      enabled: false
