apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrect
  labels:
    app: grafana
type: Opaque
data:
  # By default, admin is set to `admin2675`
  admin-user: YWRtaW4=
  admin-password: "YWRtaW4yNjc1"