apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-alert-rule-cm
  namespace: logging
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
data:
  rules.yml: |-
    "groups":
    - name: apps-rules
      rules:
      - alert: AppsErrorlog
        expr: sum by (pod,namespace)(count_over_time({pod!=""}|~ "[Ee]rror"[1m])) >= 1
        for: 1m
        labels:
          severity: warning
          category: logs
        annotations:
          title: "Application error in logs"
          messages: "Found error in POD ({{ $labels.pod }}) in namespace ({{ $labels.namespace }}) is above 1 (current value: {{ $value }})"
      - alert: NoSuchHostError
        expr: sum by (pod,namespace)(count_over_time({pod !~ "(kubemon-alertmanager-0|kubemon-alertmanager-1|loki-0|loki-1)",namespace !~ "(logging|monitoring)"}|~ "no such host"[1m])) >= 1
        for: 1m
        labels:
          severity: warning
          category: logs
        annotations:
          title: "No Such Host Error"
          messages: "No Such Host error found in POD ({{ $labels.pod }}) in namespace ({{ $labels.namespace }}) is above 1 (current value: {{ $value }})"
      - alert: OfflinPODError
        expr: sum by (pod,namespace)(count_over_time({pod !~ "(kubemon-alertmanager-0|kubemon-alertmanager-1|loki-0|loki-1)",namespace !~ "(logging|monitoring)"}|~ "1 Offline"[1m])) >= 1
        for: 1m
        labels:
          severity: warning
          category: logs
        annotations:
          title: "Offline POD Error"
          messages: "Offline POD error found in POD ({{ $labels.pod }}) in namespace ({{ $labels.namespace }}) is above 1 (current value: {{ $value }})"          