apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio-store
  labels:
    app: minio
spec:
  clusterIP: None
  ports:
  - port: 9000
    name: minio
  selector:
    app: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: minio-store
spec:
  type: NodePort
  selector:
    app: minio
  ports:
  - name: minio-console
    protocol: TCP
    port: 9090
    targetPort: 9090
  - name: minio-api
    protocol: TCP
    port: 9000
    targetPort: 9000