apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  destination:
    namespace: minio-store
    server: 'https://kubernetes.default.svc'
  source:
    path: minio-store
    repoURL: 'https://github.com/cloudcafetech/k8s-terraform'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
