apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-argocd-backup
  namespace: argo-backup
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-argocd-backup
rules:
  - apiGroups: [""]
    resources: ["pods","configmaps","secrets"]
    verbs: ["get","list","watch"]
  - apiGroups: ["argoproj.io"]
    resources: [ "*"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-role-argocd-backup
subjects:
  - kind: ServiceAccount
    name: sa-argocd-backup
    namespace: argo-backup
roleRef:
  kind: ClusterRole
  name: role-argocd-backup
  apiGroup: rbac.authorization.k8s.io